# Generated by Django 5.2.7 on 2025-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
